name: Admin CD

on:
  push:
    branches: [main]
    paths: ['admin/**']

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy Admin to AWS S3 & CloudFront

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: latest

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build admin application
        run: pnpm --filter admin build
        env:
          VITE_API_BASE_URL: ${{ secrets.VITE_API_BASE_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Deploy to S3
        run: |
          aws s3 sync admin/dist/ s3://${{ secrets.AWS_S3_BUCKET }}/admin/ --delete --exact-timestamps

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.AWS_CLOUDFRONT_DISTRIBUTION_ID }} --paths "/admin/*"

      - name: Deployment success notification
        run: |
          echo "✅ Admin application successfully deployed to AWS S3 and CloudFront cache invalidated"